source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "easy-peasy-api", path: "..", require: "easy_peasy_api"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end
